### ISSUE TITLE
Reduce the width of header and also responsive

### ISSUE THREAD

**Issue by ruchika-01p** [ruchika-01p/Art_of_Living_YOGA#1]

**Comment by daedraMex** [comment]
Can I work on this?

**Comment by ruchika-01p** [comment]
Yes sure! Assigning to you

**Comment by ruchika-01p** [comment]
Hi @Any28Flo  any updates? have you started working on this issue?

**Comment by daedraMex** [comment]
Yes, today I work on it

**Comment by shiyasmohd** [comment]
can i work on this?

**Comment by ruchika-01p** [comment]
This issue is already assigned

**Comment by ruchika-01p** [comment]
@Shiyasmohd pl check out other issues well i can assign you that which need to be work on

**Comment by ruchika-01p** [comment]
@Shiyasmohd do you want to work on this ?

**Comment by shiyasmohd** [comment]
> @Shiyasmohd do you want to work on this ?

Yes i can do....assign me

**Comment by ruchika-01p** [comment]
okay assigning to you

**Comment by Shiyasmohd** [comment]
![Screenshot 2021-10-09 144209](https://user-images.githubusercontent.com/83513144/136652130-4821d470-b889-45f4-86dc-b67d1fdacb0c.png
![Screenshot 2021-10-09 144222](https://user-images.githubusercontent.com/83513144/136652145-58e2d93e-2b91-4d49-bdd2-2f4577cb1d49.png)
)
