### ISSUE TITLE
issue currently when we clicked the nav options. Its reload the page.

### ISSUE THREAD

**Issue by Bivas-Biswas** [ruchika-01p/Art_of_Living_YOGA#10]
work

- will use routing for no reload page

**Comment by nehakalbande** [comment]
Hi @Bivas-Biswas Can you bit explain exactly what issue you are talking about?

**Comment by aaditya9899** [comment]
hey can i work on this issue , its just routing part i can do it

**Comment by Bivas-Biswas** [comment]
currently when we press the any of nav button it refresh the whole page. We know that react is  client side render library. 
so our task is - 
when press this button, it does not reload the page. just routing to the  site. @nehakalbande

**Comment by aaditya9899** [comment]
Hey can i work on this , its just routing part i can easily do it... And also would it be counted in hactoberfest?

**Comment by Bivas-Biswas** [comment]
@aaditya9899 I know man. I want to work on this. So I created this issues. If this is not solved, there is no reason to use the react .

**Comment by nehakalbande** [comment]
Sure @Bivas-Biswas Work on it. Assigning to you

**Comment by nehakalbande** [comment]
@aaditya9899 adding more issues, please have a look on it :)

**Comment by Bivas-Biswas** [comment]
@aaditya9899 , Just curios any other plan for the navbar. like -
- need to be sticky sticky or not
- hover animation
- design

**Comment by nehakalbande** [comment]
> @aaditya9899 , Just curios any other plan for the navbar. like -
> 
> * need to be sticky sticky or not
> * hover animation
> * design

@Bivas-Biswas its not needed

**Comment by Bivas-Biswas** [comment]
@nehakalbande I resolved the issue. before pull request need to solve this #18
