### ISSUE TITLE
Add tailwind css

### ISSUE THREAD

**Issue by apoorvcodes** [ruchika-01p/Art_of_Living_YOGA#11]
Tailwind css can allow more and more devs to connect to the project as many prefer it over normal css.

**Comment by apoorvcodes** [comment]
you can assign me for this and ill do it

**Comment by apoorvcodes** [comment]
@ruchika-01p

**Comment by ruchika-01p** [comment]
Yes you can do but it will change the whole css and also we have already assigned the small css related issues to others so you will have to make changes in accordance with their changes
