### ISSUE TITLE
 In Home, Courses, About only one component should be visible at a time

### ISSUE THREAD

**Issue by ruchika-01p** [ruchika-01p/Art_of_Living_YOGA#14]

**Comment by yasinbordbar** [comment]
Hi, please assign me to do this.

**Comment by ruchika-01p** [comment]
Yes sure! assigning to you.

**Comment by pri1311** [comment]
Hello @ruchika-01p  would like to work on the issue, but before I have it assigned would it be possible for you to add a screenshot?

**Comment by ruchika-01p** [comment]
connect on discord

**Comment by nehakalbande** [comment]
@pri1311 are you working on this issue?
