### ISSUE TITLE
Make the Cards proper in both Courses section

### ISSUE THREAD

**Issue by ruchika-01p** [ruchika-01p/Art_of_Living_YOGA#15]

**Comment by rajputarjun2001** [comment]
Hi @ruchika-01p, I want to work on this issue, could you please sign this to me?

**Comment by nehakalbande** [comment]
Hi @rajputarjun2001 Sure, Assigning to you

**Comment by pri1311** [comment]
Hello @ruchika-01p  would like to work on the issue, but before I have it assigned would it be possible for you to add a screenshot?

**Comment by ruchika-01p** [comment]
Yes sure connect on discord for doubts 
my id: ruchika1p#5412

**Comment by pri1311** [comment]
> Yes sure connect on discord for doubts my id: ruchika1p#5412

Have sent you a request. Please check.

**Comment by ruchika-01p** [comment]
May i know your discord username

**Comment by pri1311** [comment]
> May i know your discord username

ttttt#4528

**Comment by nehakalbande** [comment]
@pri1311 are you working on this issue?
