### ISSUE TITLE
Wrong File input Import. Major error 

### ISSUE THREAD

**Issue by Bivas-Biswas** [ruchika-01p/Art_of_Living_YOGA#18]
https://github.com/ruchika-01p/Art_of_Living_YOGA/blob/09b17d17a0673dd6d6db98ee5c0b8078606e6731/src/components/About/About.js#L12-L14

need to change 
```
import Ravikaka from '../../images/team/Ravikaka.jpg';
import Shweta from '../../images/team/Shweta.jpg';
import Vihal from '../../images/team/Vihal.jpg';
```
The real image is name start with Capital R.
So I facing the import errror

**Comment by nehakalbande** [comment]
> https://github.com/ruchika-01p/Art_of_Living_YOGA/blob/09b17d17a0673dd6d6db98ee5c0b8078606e6731/src/components/About/About.js#L12-L14
> 
> need to change
> 
> ```
> import Ravikaka from '../../images/team/Ravikaka.jpg';
> import Shweta from '../../images/team/Shweta.jpg';
> import Vihal from '../../images/team/Vihal.jpg';
> ```
> 
> The real image is name start with Capital R. So I facing the import errror

Yes correct @Bivas-Biswas its showing an error, Work on it. We'll accept the PR tonight
