### ISSUE TITLE
Make footer properly aligned

### ISSUE THREAD

**Issue by nehakalbande** [ruchika-01p/Art_of_Living_YOGA#2]

**Comment by nandan-shah** [comment]
Hey, can I work on this?

**Comment by ruchika-01p** [comment]
Yes! Assigning this to you.

**Comment by arpit282** [comment]
hello, can I also work on this?

**Comment by nehakalbande** [comment]
Hi @arpit282 This issue has already been assigned, Please have a look on other issues as well to work on :)
