### ISSUE TITLE
Make the carousel proper for testimonials section

### ISSUE THREAD

**Issue by ruchika-01p** [ruchika-01p/Art_of_Living_YOGA#3]

**Comment by daedraMex** [comment]
Can I work on this?

**Comment by ruchika-01p** [comment]
Yes sure! Assigning to you

**Comment by ruchika-01p** [comment]
hey @Any28Flo have you started working any updates

**Comment by AnimeshMore** [comment]
Hey, I would like to work on this issue.

**Comment by ruchika-01p** [comment]
okay assigning to you @AnimeshMore

**Comment by AnimeshMore** [comment]
I have solved this issue. Do let me know if any changes are required before submitting the PR.

![test 3](https://user-images.githubusercontent.com/76648444/137684890-d8ef8ecc-6fea-421f-b765-ea8c6b8a0604.jpg)
![test1](https://user-images.githubusercontent.com/76648444/137684895-1f42816f-ce4b-4044-b791-d4978b82760a.jpg)
![test2](https://user-images.githubusercontent.com/76648444/137684898-b88a5946-6510-467c-a3d3-df5e98531290.jpg)

**Comment by ruchika-01p** [comment]
@AnimeshMore I think its fine .you can submit PR
