### ISSUE TITLE
Remake cards in ABOUT US and responsive

### ISSUE THREAD

**Issue by ruchika-01p** [ruchika-01p/Art_of_Living_YOGA#4]

**Comment by nandan-shah** [comment]
Hey, can I work on this issue?

**Comment by ruchika-01p** [comment]
Yes sure! Assigning to you

**Comment by adarsharyan002** [comment]
@ruchika-01p is this issue still open?

**Comment by ruchika-01p** [comment]
This issue is already assigned to @nandan-shah 
@nandan-shah are you working on it? any updates?

**Comment by nehakalbande** [comment]
> @ruchika-01p is this issue still open?

Will you work on this issue @adarsharyan002 ?
