### ISSUE TITLE
Make Forms in the backend for courses

### ISSUE THREAD

**Issue by nehakalbande** [ruchika-01p/Art_of_Living_YOGA#5]
- Informative forms that will be displayed in the Courses 
- 2 forms are needed
- For 18+ and children

**Comment by ikabir21** [comment]
can I work on this?

**Comment by ruchika-01p** [comment]
@ikabir21 Sure, connect on discord for discussion on backend part
My id: ruchika1p#5412

**Comment by ikabir21** [comment]
sure

**Comment by KryptonANSHU** [comment]
Do let me know if any work or help is needed on this project.
Happy to Contribute 🙂

**Comment by nehakalbande** [comment]
Sure @KryptonANSHU will be adding more issues soon..
