### ISSUE TITLE
Add a central error handler for catching unhandled exceptions

### ISSUE THREAD

**Issue by gitaalekhyapaul** [ruchika-01p/Art_of_Living_YOGA#9]
# Problem Description
 - Why implement a catch-all route?
 A catch-all route catches any unhandled exception which might occur in the backend. It protects the backend from throwing raw stack traces to the frontend.

I would like to be assigned to this issue for Hacktoberfest 2021 :smile:

**Comment by ruchika-01p** [comment]
Yes sure! Good idea, assigning to you
